# Generated by Django 4.1.1 on 2022-10-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_model_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_model',
            name='pic',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
